services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ufc_manager
      POSTGRES_USER: ufc
      POSTGRES_PASSWORD: ufc
    ports:
      - "5432:5432"
    volumes:
      - ufc_pg_data:/var/lib/postgresql/data

volumes:
  ufc_pg_data:
