-- Luta em exatamente um evento: card OU card_ppv.
CREATE TABLE luta (
    id_luta         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metodo          VARCHAR(100) NOT NULL,
    resultado       VARCHAR(100) NOT NULL,
    quant_rounds    INTEGER        NOT NULL,
    id_card         BIGINT,
    id_card_ppv     BIGINT,
    id_visibilidade BIGINT         NOT NULL,
    id_juiz         BIGINT         NOT NULL,
    CONSTRAINT fk_luta_card
        FOREIGN KEY (id_card) REFERENCES card (id_card),
    CONSTRAINT fk_luta_card_ppv
        FOREIGN KEY (id_card_ppv) REFERENCES card_ppv (id_card_ppv),
    CONSTRAINT fk_luta_visibilidade
        FOREIGN KEY (id_visibilidade) REFERENCES visibilidade_luta (id_visibilidade),
    CONSTRAINT fk_luta_juiz
        FOREIGN KEY (id_juiz) REFERENCES juiz (id_juiz),
    CONSTRAINT ck_luta_um_evento
        CHECK (
               (id_card IS NOT NULL AND id_card_ppv IS NULL)
            OR (id_card IS NULL AND id_card_ppv IS NOT NULL)
        )
);
