-- UFC Manager — Esquema relacional (Projeto BD)
-- Membros: Luca Ribeiro Albuquerque, Luiz Felipe Arruda, João Cláudio Beltrão, Gabriel Belo
--
-- DDL dividido em vários arquivos (V1…V13). Ordem = ordem de execução do Flyway.
-- SGBD: PostgreSQL ou H2 (MODE=PostgreSQL).
--
-- Notas vs. dicionário: data_evento = DATE; CardPPV↔cinturão = N:N (card_ppv_cinturao);
-- luta exige exatamente um de id_card ou id_card_ppv (V11).

-- Divisões de peso (peso máximo / mínimo da categoria).
CREATE TABLE divisao (
    id_divisao   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_divisao VARCHAR(100) NOT NULL,
    peso_max     DOUBLE PRECISION NOT NULL,
    peso_min     DOUBLE PRECISION NOT NULL
);
