-- UFC Manager — DDL (fonte única: Flyway + execução manual no Postico/psql).
-- Esquema: Card e CardPPV separados; Luta com id_luta; N:N card_ppv–cinturao.
-- Compatível com H2 (dev) e PostgreSQL.

CREATE TABLE divisao (
    id_divisao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_divisao VARCHAR(100) NOT NULL,
    peso_max DOUBLE PRECISION NOT NULL,
    peso_min DOUBLE PRECISION NOT NULL
);

CREATE TABLE lutador (
    id_lutador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    peso DOUBLE PRECISION NOT NULL,
    apelido VARCHAR(100) NOT NULL,
    cartel VARCHAR(15) NOT NULL,
    nacionalidade VARCHAR(100) NOT NULL,
    id_divisao BIGINT NOT NULL,
    CONSTRAINT fk_lutador_divisao FOREIGN KEY (id_divisao) REFERENCES divisao (id_divisao)
);

CREATE TABLE treinador (
    id_treinador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_treinador VARCHAR(100) NOT NULL,
    especialidade VARCHAR(100) NOT NULL,
    id_lutador BIGINT NOT NULL,
    CONSTRAINT uk_treinador_lutador UNIQUE (id_lutador),
    CONSTRAINT fk_treinador_lutador FOREIGN KEY (id_lutador) REFERENCES lutador (id_lutador)
);

CREATE TABLE lutador_lutador (
    id_lutador_lutador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lutador1 BIGINT NOT NULL,
    id_lutador2 BIGINT NOT NULL,
    CONSTRAINT ck_lutador_par_ordem CHECK (id_lutador1 < id_lutador2),
    CONSTRAINT uk_lutador_par UNIQUE (id_lutador1, id_lutador2),
    CONSTRAINT fk_ll_l1 FOREIGN KEY (id_lutador1) REFERENCES lutador (id_lutador),
    CONSTRAINT fk_ll_l2 FOREIGN KEY (id_lutador2) REFERENCES lutador (id_lutador)
);

CREATE TABLE cinturao (
    id_cinturao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_cinturao VARCHAR(100) NOT NULL,
    id_lutador BIGINT,
    id_divisao BIGINT NOT NULL,
    CONSTRAINT fk_cinturao_lutador FOREIGN KEY (id_lutador) REFERENCES lutador (id_lutador),
    CONSTRAINT fk_cinturao_divisao FOREIGN KEY (id_divisao) REFERENCES divisao (id_divisao)
);

CREATE TABLE card (
    id_card BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cidade VARCHAR(100) NOT NULL,
    pais VARCHAR(100) NOT NULL,
    data_evento DATE NOT NULL,
    quant_lutas INTEGER NOT NULL
);

CREATE TABLE card_ppv (
    id_card_ppv BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_edicao INTEGER NOT NULL,
    preco_ppv DOUBLE PRECISION NOT NULL,
    receita_total DOUBLE PRECISION NOT NULL,
    quant_pagantes INTEGER NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    pais VARCHAR(100) NOT NULL,
    data_evento DATE NOT NULL,
    quant_lutas INTEGER NOT NULL
);

CREATE TABLE card_ppv_cinturao (
    id_card_ppv BIGINT NOT NULL,
    id_cinturao BIGINT NOT NULL,
    PRIMARY KEY (id_card_ppv, id_cinturao),
    CONSTRAINT fk_cpc_ppv FOREIGN KEY (id_card_ppv) REFERENCES card_ppv (id_card_ppv),
    CONSTRAINT fk_cpc_cin FOREIGN KEY (id_cinturao) REFERENCES cinturao (id_cinturao)
);

CREATE TABLE visibilidade_luta (
    id_visibilidade BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visibilidade VARCHAR(100) NOT NULL
);

CREATE TABLE juiz (
    id_juiz BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_juiz VARCHAR(100) NOT NULL
);

CREATE TABLE luta (
    id_luta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metodo VARCHAR(100) NOT NULL,
    resultado VARCHAR(100) NOT NULL,
    quant_rounds INTEGER NOT NULL,
    id_card BIGINT,
    id_card_ppv BIGINT,
    id_visibilidade BIGINT NOT NULL,
    id_juiz BIGINT NOT NULL,
    CONSTRAINT ck_luta_card_xor CHECK (
        (id_card IS NOT NULL AND id_card_ppv IS NULL)
        OR (id_card IS NULL AND id_card_ppv IS NOT NULL)
    ),
    CONSTRAINT fk_luta_card FOREIGN KEY (id_card) REFERENCES card (id_card),
    CONSTRAINT fk_luta_ppv FOREIGN KEY (id_card_ppv) REFERENCES card_ppv (id_card_ppv),
    CONSTRAINT fk_luta_vis FOREIGN KEY (id_visibilidade) REFERENCES visibilidade_luta (id_visibilidade),
    CONSTRAINT fk_luta_juiz FOREIGN KEY (id_juiz) REFERENCES juiz (id_juiz)
);

CREATE TABLE possui (
    id_luta BIGINT NOT NULL PRIMARY KEY,
    id_lutador_desafiante BIGINT NOT NULL,
    id_lutador_desafiado BIGINT NOT NULL,
    id_cinturao BIGINT,
    CONSTRAINT ck_possui_lutadores_distintos CHECK (id_lutador_desafiante <> id_lutador_desafiado),
    CONSTRAINT fk_possui_luta FOREIGN KEY (id_luta) REFERENCES luta (id_luta),
    CONSTRAINT fk_possui_desafiante FOREIGN KEY (id_lutador_desafiante) REFERENCES lutador (id_lutador),
    CONSTRAINT fk_possui_desafiado FOREIGN KEY (id_lutador_desafiado) REFERENCES lutador (id_lutador),
    CONSTRAINT fk_possui_cinturao FOREIGN KEY (id_cinturao) REFERENCES cinturao (id_cinturao)
);
