-- Atletas; FK para divisão.
CREATE TABLE lutador (
    id_lutador    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(100) NOT NULL,
    peso          DOUBLE PRECISION NOT NULL,
    apelido       VARCHAR(100) NOT NULL,
    cartel        VARCHAR(15)  NOT NULL,
    nacionalidade VARCHAR(100) NOT NULL,
    id_divisao    BIGINT         NOT NULL,
    CONSTRAINT fk_lutador_divisao
        FOREIGN KEY (id_divisao) REFERENCES divisao (id_divisao)
);
