-- Par de lutadores (histórico, ranking, confronto direto).
CREATE TABLE lutador_lutador (
    id_lutador_lutador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lutador1        BIGINT NOT NULL,
    id_lutador2        BIGINT NOT NULL,
    CONSTRAINT fk_lutador_lutador_1
        FOREIGN KEY (id_lutador1) REFERENCES lutador (id_lutador),
    CONSTRAINT fk_lutador_lutador_2
        FOREIGN KEY (id_lutador2) REFERENCES lutador (id_lutador),
    CONSTRAINT ck_lutador_lutador_distintos
        CHECK (id_lutador1 <> id_lutador2)
);
