-- Treinador ligado a um lutador (1:1 no modelo JPA).
CREATE TABLE treinador (
    id_treinador   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_treinador VARCHAR(100) NOT NULL,
    especialidade  VARCHAR(100) NOT NULL,
    id_lutador     BIGINT         NOT NULL,
    CONSTRAINT fk_treinador_lutador
        FOREIGN KEY (id_lutador) REFERENCES lutador (id_lutador),
    CONSTRAINT uq_treinador_lutador
        UNIQUE (id_lutador)
);
