-- Cinturão da divisão; id_lutador NULL = título vago.
CREATE TABLE cinturao (
    id_cinturao   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_cinturao VARCHAR(100) NOT NULL,
    id_lutador    BIGINT,
    id_divisao    BIGINT NOT NULL,
    CONSTRAINT fk_cinturao_lutador
        FOREIGN KEY (id_lutador) REFERENCES lutador (id_lutador),
    CONSTRAINT fk_cinturao_divisao
        FOREIGN KEY (id_divisao) REFERENCES divisao (id_divisao)
);
