-- Fight Night (evento não PPV).
CREATE TABLE card (
    id_card     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cidade      VARCHAR(100) NOT NULL,
    pais        VARCHAR(100) NOT NULL,
    data_evento DATE           NOT NULL,
    quant_lutas INTEGER        NOT NULL
);
