-- Pay-per-view: edição, financeiro, local, data, quantidade de lutas.
CREATE TABLE card_ppv (
    id_card_ppv    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_edicao     INTEGER        NOT NULL,
    preco_ppv      DOUBLE PRECISION NOT NULL,
    receita_total  DOUBLE PRECISION NOT NULL,
    quant_pagantes INTEGER        NOT NULL,
    cidade         VARCHAR(100) NOT NULL,
    pais           VARCHAR(100) NOT NULL,
    data_evento    DATE           NOT NULL,
    quant_lutas    INTEGER        NOT NULL
);
